#!/bin/bash
# From https://github.com/tasket/Qubes-VM-hardening
# installer version 0.9.4

set -e
[ `id -u` -eq 0 ] || exit


if [[ ! -e "/etc/sudoers.d/qubes" ]]; then
    echo "The 'qubes-core-agent-passwordless-root' package does not appear"
    echo "to be present or configured; sudo autoconfiguration skipped."
    exit 0
fi

if [[ ! -e "/etc/debian_version" && ! -e "/etc/fedora-release" && ! -e "/etc/arch-release" ]]; then
    echo "Debian/Fedora/Arch based template required for sudo autoconfiguration."
    echo "See https://qubes-os.org/doc/vm-sudo for manual instructions."
    exit 1
fi

if [[ "$1" = "--force" ]]; then
    force=1
else
    force=0
fi
if [[ -f "/etc/pam.d/common-auth" ]]; then 
    authFile="common-auth"
elif [[ -f "/etc/pam.d/system-auth" ]]; then 
    authFile="system-auth"
else 
    echo "pam.d/{common-auth||system-auth}} not found" 
    exit 1
fi
if grep -q '^auth .* dom0\squbes\.VMAuth' /etc/pam.d/$authFile && [ $force = 0 ]; then
    echo "System appears already configured for sudo prompts."
    echo "To force re-configuration run 'configure-sudo-prompt --force'."
    exit 0
fi


echo -e "\n--+  Enable yes/no authentication prompt for sudo  +--
Warning: Before opting for this change a backup or clone
should me made of this template!"
if [ $force = 0 ]; then
    read -p "Configure sudo authentication prompt now? (y/n): " answer
fi
if [[ $answer == @(y|Y) ]] || [ $force = 1 ]; then
    mv -fb /etc/pam.d/$authFile /etc/pam.d/$authFile~
    cat >/etc/pam.d/$authFile <<_EOF
auth  [success=1 default=ignore]  pam_exec.so seteuid /usr/lib/qubes/qrexec-client-vm dom0 qubes.VMAuth /bin/grep -q ^1$
auth  requisite  pam_deny.so
auth  required   pam_permit.so
_EOF

fi
if [[ $authFile == "system-auth" ]]; then
    cat >> /etc/pam.d/$authFile <<_EOF
account     required      pam_unix.so

password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=
password    sufficient    pam_unix.so try_first_pass use_authtok nullok sha512 shadow
password    required      pam_deny.so

session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
-session     optional      pam_systemd.so
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so  
_EOF

fi
#    sed -i 's/^user ALL=(ALL) NOPASSWD: ALL/user ALL=(ALL) ALL/' /etc/sudoers.d/qubes
    sed -i 's/^user/#user/' /etc/sudoers.d/qubes
    echo 'user ALL=(ALL) ALL' >>/etc/sudoers.d/qubes

    sed -ri 's/^(auth[[:space:]]sufficient[[:space:]]pam_permit.so)/#\1/' /etc/pam.d/su

    mv -f /etc/polkit-1/rules.d/00-qubes-allow-all.rules \
      /etc/polkit-1/rulesd_00-qubes-allow-all.rules.bak || true
    mv -f /etc/polkit-1/localauthority/50-local.d/qubes-allow-all.pkla \
      /etc/polkit-1/localauthority_50-locald_qubes-allow-all.pkla.bak || true

    echo "Done."

    echo '
Next.... Enable auth prompts in dom0 with the following commands:
  [user@dom0 ~]$ sudo su -
  [root@dom0 /]# echo "/usr/bin/echo 1" >/etc/qubes-rpc/qubes.VMAuth
  [root@dom0 /]# chmod +x /etc/qubes-rpc/qubes.VMAuth
  [root@dom0 /]# echo "@anyvm dom0 ask,default_target=dom0" \
    >/etc/qubes-rpc/policy/qubes.VMAuth

'
